
import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import 'katex/dist/katex.min.css';

import { ThemeProvider } from "@/components/shared/theme-provider";

import localFont from 'next/font/local'
import { StyleProvider } from "@/lib/StyleContext";
import Navbar from "@/components/shared/navbar";
import { Toaster } from "@/components/ui/sonner";

const zentry = localFont({
  src: './fonts/zentry-regular.woff2',
  variable: '--font-zentry'
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

const saira = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${zentry.variable} ${poppins.variable} ${saira.variable}  antialiased`}
        >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange>
            <StyleProvider> 
          <div className="relative">
  
        <Navbar />
       
        <main className="">
          {children}
        </main>
          </div>
          <Toaster />
      </StyleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
