import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/navbar";
import { ThemeProvider } from "@/components/shared/theme-provider";

import localFont from 'next/font/local'
 
const zentry = localFont({
  src: './fonts/zentry-regular.woff2',
  variable: '--font-zentry'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${zentry.className} antialiased`}
      >
        <ThemeProvider
        attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

        <Navbar />
        <main  className="flex min-h-screen flex-col overflow-x-hidden ">
        {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
